//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Student_Firstname {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Student_Firstname"]));
            }
            set
            {
                this["Student_Firstname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Student_Lastname {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Student_Lastname"]));
            }
            set
            {
                this["Student_Lastname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Student_Fathername {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Student_Fathername"]));
            }
            set
            {
                this["Student_Fathername"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Student_Codemeli {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Student_Codemeli"]));
            }
            set
            {
                this["Student_Codemeli"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Student_Birthdate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Student_Birthdate"]));
            }
            set
            {
                this["Student_Birthdate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Teacher_Firstname {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teacher_Firstname"]));
            }
            set
            {
                this["Teacher_Firstname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Teacher_Lastname {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teacher_Lastname"]));
            }
            set
            {
                this["Teacher_Lastname"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Teacher_Fathername {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teacher_Fathername"]));
            }
            set
            {
                this["Teacher_Fathername"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Teacher_Codemeli {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teacher_Codemeli"]));
            }
            set
            {
                this["Teacher_Codemeli"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Teacher_Birthdate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Teacher_Birthdate"]));
            }
            set
            {
                this["Teacher_Birthdate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Math {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Math"]));
            }
            set
            {
                this["Math"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Physic {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Physic"]));
            }
            set
            {
                this["Physic"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Shimi {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Shimi"]));
            }
            set
            {
                this["Shimi"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Arabi {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Arabi"]));
            }
            set
            {
                this["Arabi"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Adabiat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Adabiat"]));
            }
            set
            {
                this["Adabiat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Average {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Average"]));
            }
            set
            {
                this["Average"] = value;
            }
        }
    }
}
